twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_4_layout.html.twig' ]
  globals:
    CompanyDetails: '@App\Services\CompanyDetails'
    CountPendingWebsiteInquiries: '@App\Services\CountPendingWebsiteInquiries'
    Product: '@App\Services\Product'
    WeatherService: '@App\Services\WeatherService'




when@test:
  twig:
    strict_variables: true

