twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        CompanyDetails: '@App\Services\CompanyDetails'
        Product: '@App\Services\Product'
        CountPendingWebsiteInquiries: '@App\Services\CountPendingWebsiteInquiries'

        BankBalanceOnAsOfDate: '@App\Services\BankBalanceOnAsOfDate'
        CountPhotos: '@App\Services\CountPhotos'
        CountPendingItems: '@App\Services\CountPendingItems'
        CountAllocatedWebsites: '@App\Services\CountAllocatedWebsites'
        FindUser: '@App\Services\FindUser'
        FXRatesOnAsOfDate: '@App\Services\FXRatesOnAsOfDate'
        Investment: '@App\Services\Investment'
        MarketDataPrice: '@App\Services\MarketDataPrice'
        PhotoAuthorsByLocation: '@App\Services\PhotoAuthorsByLocation'
        StaticText: '@App\Services\StaticText'
        TaxYear: '@App\Services\TaxYear'
        TaxYearCalcs: '@App\Services\TaxYearCalcs'
        UserIsHouseGuest: '@App\Services\UserIsHouseGuest'
        WebPages: '@App\Services\WebPages'



