twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_4_layout.html.twig' ]
  globals:
    CompanyDetails: '@App\Services\ATS\CompanyDetails'
    CountPendingWebsiteInquiries: '@App\Services\ATS\CountPendingWebsiteInquiries'
    Product: '@App\Services\ATS\Product'
    WeatherService: '@App\Services\ATS\WeatherService'

    BankBalanceOnAsOfDate: '@App\Services\ProjectSpecific\BankBalanceOnAsOfDate'
    CountDaysByCountry: '@App\Services\ProjectSpecific\CountDaysByCountry'
    CountPhotos: '@App\Services\ProjectSpecific\CountPhotos'
    CountPendingItems: '@App\Services\ProjectSpecific\CountPendingItems'
    CountAllocatedWebsites: '@App\Services\ProjectSpecific\CountAllocatedWebsites'
    FindUser: '@App\Services\ProjectSpecific\FindUser'
    FXRatesOnAsOfDate: '@App\Services\ProjectSpecific\FXRatesOnAsOfDate'
    Investment: '@App\Services\ProjectSpecific\Investment'
    LocationByDate: '@App\Services\ProjectSpecific\LocationByDate'
    MarketDataPrice: '@App\Services\ProjectSpecific\MarketDataPrice'
    PhotoAuthorsByLocation: '@App\Services\ProjectSpecific\PhotoAuthorsByLocation'
    TaxYear: '@App\Services\ProjectSpecific\TaxYear'
    TaxYearCalcs: '@App\Services\ProjectSpecific\TaxYearCalcs'
    UserIsHouseGuest: '@App\Services\ProjectSpecific\UserIsHouseGuest'



