twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        Investment: '@App\Services\Investment'
        StaticText: '@App\Services\StaticText'
        TaxYear: '@App\Services\TaxYear'

