twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_4_layout.html.twig' ]
  globals:
    CompanyDetails: '@App\Services\ATS\CompanyDetails'
    CountPendingWebsiteInquiries: '@App\Services\ATS\CountPendingWebsiteInquiries'
    Product: '@App\Services\ATS\Product'
    WeatherService: '@App\Services\ATS\WeatherService'

    BankBalanceOnAsOfDate: '@App\Services\Project_Specific\BankBalanceOnAsOfDate'
    CountDaysByCountry: '@App\Services\Project_Specific\CountDaysByCountry'
    CountPhotos: '@App\Services\Project_Specific\CountPhotos'
    CountPendingItems: '@App\Services\Project_Specific\CountPendingItems'
    CountAllocatedWebsites: '@App\Services\Project_Specific\CountAllocatedWebsites'
    FindUser: '@App\Services\Project_Specific\FindUser'
    FXRatesOnAsOfDate: '@App\Services\Project_Specific\FXRatesOnAsOfDate'
    Investment: '@App\Services\Project_Specific\Investment'
    LocationByDate: '@App\Services\Project_Specific\LocationByDate'
    MarketDataPrice: '@App\Services\Project_Specific\MarketDataPrice'
    PhotoAuthorsByLocation: '@App\Services\Project_Specific\PhotoAuthorsByLocation'
    TaxYear: '@App\Services\Project_Specific\TaxYear'
    TaxYearCalcs: '@App\Services\Project_Specific\TaxYearCalcs'
    UserIsHouseGuest: '@App\Services\Project_Specific\UserIsHouseGuest'



