# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    files_upload_default_directory: '%kernel.project_dir%/public/administration/attachments/Files'
    file_attachments_directory: '%kernel.project_dir%/public/administration/attachments/FileAttachments'
    files_cv_directory: '%kernel.project_dir%/public/administration/attachments/CV'
    import_user_directory: '%kernel.project_dir%/public/administration/import/'
    import_photo_directory: '%kernel.project_dir%/public/administration/img/photogallery/'
    investments_attachment_directory: '%kernel.project_dir%/public/administration/attachments/Investments'
    investments_future_comms_attachment_directory: '%kernel.project_dir%/public/administration/attachments/Investments/InvestmentsFutureComms'
    garmin_attachments_directory: '%kernel.project_dir%/public/administration/attachments/GarminGPXFiles'
    jpm_ic_history_directory: '%kernel.project_dir%/public/administration/attachments/JPMICHistory'
    photos_upload_default_directory: '%kernel.project_dir%/public/photos/'
    winelist_directory: '%kernel.project_dir%/public/administration/img/winelist'
    tax_documents_attachments_directory: '%kernel.project_dir%/public/administration/attachments/TaxDocuments'
    tax_supporting_documents_attachments_directory: '%kernel.project_dir%/public/administration/attachments/TaxDocuments/TaxSupportingDocuments'
    tourist_attraction_photos_directory: '%kernel.project_dir%/public/administration/attachments/touristattractionphotos'
    temporary_attachment_directory: '%kernel.project_dir%/public/temporary/'
    user_attachments_directory: '%kernel.project_dir%/public/administration/attachments/Users/'
    website_photos_directory: '%kernel.project_dir%/public/administration/attachments/websitephotos'
    scraper: '%kernel.project_dir%/public/scrape/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
